Hfa 47
RandomUserIK/SpartaWebPage-backend pull request #4
Opened 2021-03-18 17:21 UTC by trofoSK

2021-03-19 06:46 UTC, RandomUserIK requested changes

2021-03-19 06:46 UTC, RandomUserIK commented on src/main/java/sk/hfa/databases/projects/domains/repositories/FileSystemRepository.java
> +        } catch (Exception e) {
tu sa neda nejaka konkretnejsia vynimka odchytit?

2021-03-19 06:46 UTC, RandomUserIK commented on src/main/java/sk/hfa/databases/projects/services/IndividualProjectService.java
> +        Optional<IndividualProject> post = individualProjectRepository.findByProjectName(projectName);
mozes rovno dat `return individualProjectRepository.findByProjectName(projectName).orElse(null)`

2021-03-19 06:46 UTC, RandomUserIK commented on src/main/java/sk/hfa/databases/projects/services/IndividualProjectService.java
> +        Optional<IndividualProject> post = individualProjectRepository.findById(id);
mozes rovno dat return `individualProjectRepository.findById(projectName).orElse(null)`

2021-03-19 06:46 UTC, RandomUserIK commented on src/main/java/sk/hfa/databases/projects/domains/TextSections.java
> +public class TextSections {
tu by som zmenil mozno nazov na `TextSection` kedze sa jedna o entitu a potom mas pekne v IndividualProject triede `List<TextSection> textSections`

2021-03-20 12:30 UTC, RandomUserIK approved these changes

2021-03-21 11:08 UTC, b0tka approved these changes

2021-03-21 14:24 UTC, merged